import React, { useEffect, useState, useMemo } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { Search, FileSearch, Radio, ArrowUpDown, FileText, ChevronDown, Sparkles, Download } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { useLanguage } from "@/lib/LanguageContext";
import EmptyState from "@/components/EmptyState";
import ReportView from "@/components/report/ReportView";
import RiskBadge from "@/components/RiskBadge";
import WaterGradeBadge, { getWaterGrade } from "@/components/report/WaterGradeBadge";
import ReportSummaryCards from "@/components/report/ReportSummaryCards";
import ConnectionStatusBadge from "@/components/ConnectionStatusBadge";
import RiskTimeline from "@/components/report/RiskTimeline";
import AISummary from "@/components/report/AISummary";
import ReportCompare from "@/components/report/ReportCompare";
import { classifyParameter } from "@/lib/waterAnalysis";
import moment from "moment";

const FILTERS = [
  { key: "all", label: "All", color: "from-purple-500 to-violet-600" },
  { key: "safe", label: "Safe", color: "from-emerald-500 to-teal-500" },
  { key: "moderate", label: "Moderate", color: "from-amber-500 to-orange-500" },
  { key: "danger", label: "Unsafe", color: "from-rose-500 to-red-500" },
];

function formatSensorValue(type, value) {
  if (value === null || value === undefined || value < 0) return "N/A";
  if (type === "tds" || type === "turbidity") return Math.round(value);
  if (type === "temperature" || type === "ph") return Math.round(value * 10) / 10;
  return value;
}

function getTopDiseases(diseaseRisks, limit = 2) {
  if (!diseaseRisks) return [];
  const risks = typeof diseaseRisks === "string" ? JSON.parse(diseaseRisks) : diseaseRisks;
  return Object.entries(risks || {})
    .sort(([, a], [, b]) => b - a)
    .slice(0, limit);
}

async function downloadScanPDF(scan, e) {
  e.stopPropagation();
  try {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    // Header band
    doc.setFillColor(6, 182, 212);
    doc.rect(0, 0, 210, 32, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("AquaSentinel AI", 20, 15);
    doc.setFontSize(11);
    doc.text("Water Quality Diagnostic Report", 20, 24);

    // Sample info
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(16);
    doc.text(scan.sample_name || "Untitled Scan", 20, 48);
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(`Date: ${moment(scan.created_date).format("lll")}`, 20, 56);
    doc.text(`Scan ID: ${scan.id?.slice(-8) || "N/A"}`, 20, 62);

    // Key metrics
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(13);
    doc.text("Summary", 20, 76);
    doc.setDrawColor(220, 220, 220);
    doc.line(20, 78, 190, 78);

    doc.setFontSize(11);
    doc.text(`Health Score: ${scan.health_score}/100`, 20, 88);
    doc.text(`Risk Level: ${scan.risk_level.toUpperCase()}`, 20, 95);
    doc.text(`Water Grade: ${getWaterGrade(scan.health_score).letter}`, 20, 102);

    // Sensor readings
    doc.setFontSize(13);
    doc.text("Sensor Readings", 20, 118);
    doc.line(20, 120, 190, 120);

    doc.setFontSize(11);
    doc.text(`pH: ${formatSensorValue("ph", scan.ph)}`, 20, 130);
    doc.text(`TDS: ${formatSensorValue("tds", scan.tds)} ppm`, 20, 137);
    doc.text(`Temperature: ${formatSensorValue("temperature", scan.temperature)} \u00b0C`, 20, 144);
    doc.text(`Turbidity: ${formatSensorValue("turbidity", scan.turbidity)} NTU`, 20, 151);

    // Disease risks
    const risks = typeof scan.disease_risks === "string" ? JSON.parse(scan.disease_risks) : (scan.disease_risks || {});
    const diseaseEntries = Object.entries(risks).sort(([, a], [, b]) => b - a);

    doc.setFontSize(13);
    doc.text("Disease Risk Assessment", 20, 167);
    doc.line(20, 169, 190, 169);

    doc.setFontSize(11);
    let y = 179;
    diseaseEntries.forEach(([disease, risk]) => {
      doc.text(`${disease.charAt(0).toUpperCase() + disease.slice(1)}: ${risk}%`, 20, y);
      y += 7;
    });

    // AI Analysis excerpt
    if (scan.ai_analysis) {
      if (y > 240) { doc.addPage(); y = 20; }
      doc.setFontSize(13);
      doc.text("AI Medical Analysis", 20, y);
      doc.line(20, y + 2, 190, y + 2);
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      const lines = doc.splitTextToSize(scan.ai_analysis.split("\n\n")[0], 170);
      doc.text(lines, 20, y + 12);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by AquaSentinel AI - Water Quality Intelligence Platform", 20, 285);

    doc.save(`water-report-${scan.id?.slice(-8) || "scan"}.pdf`);
  } catch (err) {
    console.error("PDF generation failed:", err);
  }
}

const PAGE_FONT_STYLE = { fontFamily: "'Manrope', ui-sans-serif, system-ui, sans-serif" };
const PAGE_FONT_CSS = `.ai-page h1,.ai-page h2,.ai-page h3,.ai-page h4,.ai-page h5,.ai-page h6,.ai-page .font-heading{font-family:'Manrope',ui-sans-serif,system-ui,sans-serif}`;

export default function AIAnalysis() {
  const { scanId } = useParams();
  const navigate = useNavigate();
  const { t } = useLanguage();
  const [scans, setScans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedScan, setSelectedScan] = useState(null);
  const [scanLoading, setScanLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [sortBy, setSortBy] = useState("newest");
  const [expandedId, setExpandedId] = useState(null);
  const [timeFilter, setTimeFilter] = useState("30d");

  useEffect(() => {
    async function loadData() {
      try {
        const results = await base44.entities.Scan.list("-created_date", 200);
        setScans(results || []);
      } catch (e) {} finally { setLoading(false); }
    }
    loadData();
  }, []);

  useEffect(() => {
    if (scanId) {
      setScanLoading(true);
      async function loadScan() {
        try {
          const scan = await base44.entities.Scan.get(scanId);
          setSelectedScan(scan);
        } catch (e) { setSelectedScan(null); } finally { setScanLoading(false); }
      }
      loadScan();
    } else {
      setSelectedScan(null);
    }
  }, [scanId]);

  const filteredScans = useMemo(() => {
    let result = scans;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter((s) =>
        (s.sample_name || "").toLowerCase().includes(q) ||
        (s.water_source_name || "").toLowerCase().includes(q) ||
        (s.location_name || "").toLowerCase().includes(q)
      );
    }
    if (filter !== "all") {
      result = result.filter((s) => s.risk_level === filter);
    }
    if (sortBy === "oldest") {
      result = [...result].reverse();
    }
    return result;
  }, [scans, searchQuery, filter, sortBy]);

  const pageWrapper = (children) => (
    <div className="ai-page" style={PAGE_FONT_STYLE}>
      <style>{PAGE_FONT_CSS}</style>
      {children}
    </div>
  );

  // ===== Loading state =====
  if (loading) {
    return pageWrapper(
      <div className="flex items-center justify-center py-20">
        <div className="w-8 h-8 border-4 border-purple-500/20 border-t-purple-500 rounded-full animate-spin" />
      </div>
    );
  }

  // ===== Report Viewer Mode =====
  if (scanId) {
    if (scanLoading) {
      return pageWrapper(
        <div className="flex items-center justify-center py-20">
          <div className="w-8 h-8 border-4 border-purple-500/20 border-t-purple-500 rounded-full animate-spin" />
        </div>
      );
    }
    if (!selectedScan) {
      return pageWrapper(
        <EmptyState
          title="Report Not Found"
          description="This scan report may have been deleted."
          illustration="history"
          action={
            <button onClick={() => navigate("/analysis")} className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-gradient-to-r from-purple-500 to-violet-600 text-white font-medium">
              <FileSearch className="w-5 h-5" /> Back to Reports
            </button>
          }
        />
      );
    }
    return pageWrapper(
      <ReportView
        scan={selectedScan}
        allScans={scans}
        onBack={() => navigate("/analysis")}
        onDeleted={() => navigate("/analysis")}
        onNavigate={(id) => navigate(`/analysis/${id}`)}
      />
    );
  }

  // ===== Empty state =====
  if (scans.length === 0) {
    return pageWrapper(
      <EmptyState
        title={t("noScansYet")}
        description={t("noScansYetDesc")}
        action={
          <button onClick={() => navigate("/monitor")} className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-gradient-to-r from-purple-500 to-violet-600 text-white font-medium hover:shadow-lg hover:shadow-purple-500/25 transition-all">
            <Radio className="w-5 h-5" /> {t("startMonitoring")}
          </button>
        }
      />
    );
  }

  // ===== List View =====
  return pageWrapper(
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-purple-500 to-violet-600 flex items-center justify-center shadow-xl shadow-purple-500/25">
              <FileSearch className="w-7 h-7 text-white" />
            </div>
            <div>
              <h1 className="text-[38px] font-bold leading-tight tracking-tight">AI Diagnostic Center</h1>
              <p className="text-[14px] text-muted-foreground mt-0.5">{scans.length} report{scans.length !== 1 ? "s" : ""} on record · Real-time water quality intelligence</p>
              <div className="mt-2"><ConnectionStatusBadge /></div>
            </div>
          </div>
          <ReportCompare scans={scans} onNavigate={(id) => navigate(`/analysis/${id}`)} t={t} />
        </div>
      </motion.div>

      {/* Summary Stats */}
      <ReportSummaryCards scans={scans} />

      {/* AI Risk Trend Chart */}
      <RiskTimeline scans={scans} timeFilter={timeFilter} onTimeFilterChange={setTimeFilter} />

      {/* AI Intelligence Summary */}
      <AISummary scans={scans} />

      {/* Search + Sort */}
      <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.1 }} className="flex items-center gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by sample name, source, or location..."
            className="w-full pl-10 pr-4 py-3 rounded-2xl glass border border-border text-[15px] focus:outline-none focus:border-purple-500/40"
          />
        </div>
        <button
          onClick={() => setSortBy(sortBy === "newest" ? "oldest" : "newest")}
          className="inline-flex items-center gap-1.5 px-4 py-3 rounded-2xl glass border border-border text-sm font-medium hover:bg-muted/50 transition-colors whitespace-nowrap"
        >
          <ArrowUpDown className="w-4 h-4" />
          {sortBy === "newest" ? "Newest" : "Oldest"}
        </button>
      </motion.div>

      {/* Filter tabs */}
      <div className="flex gap-2 flex-wrap">
        {FILTERS.map((f) => (
          <button
            key={f.key}
            onClick={() => setFilter(f.key)}
            className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${
              filter === f.key ? `bg-gradient-to-r ${f.color} text-white shadow-lg` : "glass text-muted-foreground hover:text-foreground"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Report list */}
      {filteredScans.length === 0 ? (
        <div className="glass rounded-3xl p-12 text-center">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
          <p className="text-muted-foreground">No reports found matching your search.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {filteredScans.map((scan, idx) => {
            const isExpanded = expandedId === scan.id;
            const aiConfidence = scan.ai_confidence || Math.min(98, 82 + Math.round((100 - scan.health_score) * 0.15));
            const topDiseases = getTopDiseases(scan.disease_risks, 2);
            const grade = getWaterGrade(scan.health_score);

            return (
              <motion.div
                key={scan.id || idx}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: Math.min(idx * 0.04, 0.4) }}
                className={`premium-card overflow-hidden transition-all ${isExpanded ? "border-purple-500/20" : ""}`}
              >
                <div
                  onClick={() => setExpandedId(isExpanded ? null : scan.id)}
                  className="p-5 cursor-pointer"
                >
                  <div className="flex items-start justify-between gap-3 mb-3">
                    <div className="flex items-center gap-3 min-w-0 flex-1">
                      <WaterGradeBadge score={scan.health_score} size="lg" />
                      <div className="min-w-0 flex-1">
                        <p className="font-semibold text-[16px] truncate">{scan.sample_name || "Untitled Scan"}</p>
                        <p className="text-[13px] text-muted-foreground mt-0.5">{moment(scan.created_date).format("lll")}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg glass border border-border text-xs">
                        <Sparkles className="w-3 h-3 text-purple-400" />
                        <span className="font-bold">{aiConfidence}%</span>
                      </span>
                      <RiskBadge level={scan.risk_level} label={t(scan.risk_level)} size="sm" />
                      <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform flex-shrink-0 ${isExpanded ? "rotate-180" : ""}`} />
                    </div>
                  </div>

                  {/* Key sensor values row */}
                  <div className="flex items-center gap-3 text-[13px] flex-wrap mb-2">
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg glass border border-border">
                      <span className="text-muted-foreground">Score</span>
                      <span className="font-bold">{scan.health_score}/100</span>
                    </span>
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg glass border border-border">
                      <span className="text-muted-foreground">pH</span>
                      <span className="font-semibold">{formatSensorValue("ph", scan.ph)}</span>
                    </span>
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg glass border border border-border">
                      <span className="text-muted-foreground">TDS</span>
                      <span className="font-semibold">{formatSensorValue("tds", scan.tds)}</span>
                    </span>
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg glass border border-border">
                      <span className="text-muted-foreground">Turb</span>
                      <span className="font-semibold">{formatSensorValue("turbidity", scan.turbidity)}</span>
                    </span>
                    {scan.water_source_name && <span className="text-muted-foreground truncate">{scan.water_source_name}</span>}
                  </div>

                  {/* Top predicted diseases */}
                  {topDiseases.length > 0 && (
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-[11px] text-muted-foreground font-medium">Predicted:</span>
                      {topDiseases.map(([disease, risk]) => (
                        <span key={disease} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md glass border border-border text-[11px]">
                          <span className="text-muted-foreground capitalize">{disease}</span>
                          <span className={`font-bold ${risk < 15 ? "text-safe" : risk < 40 ? "text-warning" : "text-danger"}`}>{risk}%</span>
                        </span>
                      ))}
                    </div>
                  )}
                </div>

                {/* Expandable content */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <div className="px-5 pb-5 pt-1 border-t border-border/50">
                        {/* Sensor grid */}
                        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">
                          {[
                            { key: "ph", label: "pH", unit: "" },
                            { key: "tds", label: "TDS", unit: "ppm" },
                            { key: "temperature", label: "Temp", unit: "°C" },
                            { key: "turbidity", label: "Turbidity", unit: "NTU" },
                          ].map(({ key, label, unit }) => {
                            const val = formatSensorValue(key, scan[key]);
                            const status = classifyParameter(key, scan[key]);
                            const color = status === "safe" ? "text-safe" : status === "moderate" ? "text-warning" : "text-danger";
                            return (
                              <div key={key} className="rounded-xl glass border border-border/50 p-3 text-center">
                                <p className="text-[10px] text-muted-foreground uppercase tracking-wide">{label}</p>
                                <p className={`text-lg font-bold ${color}`}>{val}{val !== "N/A" && unit && <span className="text-xs text-muted-foreground ml-0.5">{unit}</span>}</p>
                              </div>
                            );
                          })}
                        </div>

                        {/* AI analysis excerpt */}
                        {scan.ai_analysis && (
                          <p className="text-[13px] text-muted-foreground leading-relaxed mt-3 line-clamp-3">
                            {scan.ai_analysis.split("\n\n")[0]}
                          </p>
                        )}

                        {/* Action buttons */}
                        <div className="flex items-center gap-2 mt-4">
                          <button
                            onClick={(e) => downloadScanPDF(scan, e)}
                            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl glass border border-border text-sm font-medium hover:bg-muted/50 transition-colors"
                          >
                            <Download className="w-4 h-4" /> Download PDF
                          </button>
                          <button
                            onClick={() => navigate(`/analysis/${scan.id}`)}
                            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-purple-500 to-violet-600 text-white text-sm font-medium hover:shadow-lg transition-all"
                          >
                            <FileText className="w-4 h-4" /> View Full Report
                          </button>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      )}
    </div>
  );
}